project:
  type: website
  output-dir: docs

website:
  title: "Soil Science Division"
  sidebar:
    logo: soils.png
    favicon: soils.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: News Feed

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 270px    # Narrower left sidebar (default is ~250-300px)
      margin-width: 130px     # Narrower right sidebar (TOC/Margin)
      body-width: 1100px      # Much wider center panel