project:
  type: website
  output-dir: docs

website:
  title: "Soil Science Division"
  sidebar:
    logo: soils.png
    favicon: soils.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: News Feed

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



