project:
  type: website
  output-dir: docs

website:
  title: "Soil Science Division"
  sidebar:
    logo: ssc.png
    favicon: soils.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: News Feed
      - href: research.qmd
        text: Research Dashboard
  page-footer:
    background: light # Options: light, dark, or a specific hex color
    border: true
    center: |
      Made with <i class="bi bi-heart-fill" style="color: #e25555;"></i> by the <img src="soils.png" alt="Logo" style="height:150px; vertical-align:middle; margin: 0 5px;"> Team

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 270px    # Narrower left sidebar (default is ~250-300px)
      margin-width: 130px     # Narrower right sidebar (TOC/Margin)
      body-width: 1100px      # Much wider center panel