---
title: "Website Launch"
author: "Villasica LJ"
date: "2025-12-27"
categories: [sidequest, projects]
---

## A new beginning

We are excited to announce the launch of our new website! This has been a dream of the Soil Science Division (SSD) of the Caraga State University - College of Agriculture and Agri-Industries (CSU-CAA) to have a single "go to" page to showcase (in as much details as we want) the activities from Instruction, Research, Development, Extension and Production areas. Moreover, this platform will also give as a window to be reach by anyone globally.

> A stable and functional site where all things important to the division and to our stakeholders (e.g. Students and Farmers) is a vital component to our goal of driving change across all boundaries.

This is not just a website that informs, but also a site where our students and other stakeholders, can use web-based applications (will be updating soon) specially developed by our team to meet soil data analysis and visualization needs.

In the future, your story might be featured in one of our News here.

Celebrate with us! share this to your online socials and give a like to this post!
